import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/sidebar/AppSidebar";
import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    redirect("/login");
  }
  const profile = await prisma.profile.findUnique({
    where: { id: user.id },
  });
  if (!profile || !profile.isActive) {
    await supabase.auth.signOut();
    redirect("/login");
  }

  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <SidebarProvider>
          <AppSidebar profile={profile} role={profile.role} />
          <main className="flex-1">{children}</main>
        </SidebarProvider>
      </body>
    </html>
  );
}
