import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { SidebarProvider, SidebarInset, SidebarTrigger } from "@/components/ui/sidebar";
import { Separator } from "@/components/ui/separator";
import AppSidebar from "@/components/sidebar/AppSidebar";
import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { QueryProvider } from "@/providers/queryProvider";
import { NotificationBell } from "@/components/NotificationBell";
import { Toaster } from "@/components/ui/toaster";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    redirect("/login");
  }
  const profile = await prisma.profile.findUnique({
    where: { id: user.id },
  });
  if (!profile || !profile.isActive) {
    await supabase.auth.signOut();
    redirect("/login");
  }

  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <QueryProvider>
          <TooltipProvider>
            <SidebarProvider>
              <AppSidebar profile={profile} role={profile.role} />
              <SidebarInset>
                <header className="flex h-14 shrink-0 items-center justify-between px-4 border-b bg-background/50 backdrop-blur-md sticky top-0 z-10 transition-all duration-200">
                  <div className="flex items-center gap-2">
                    <SidebarTrigger />
                    <Separator orientation="vertical" className="h-6 mx-2" />
                    <div className="flex items-center gap-2 text-sm font-medium">
                      <span className="text-muted-foreground/60">Whispyr CRM</span>
                      <span className="text-muted-foreground/30">/</span>
                      <span className="capitalize text-foreground/80">{profile.role.toLowerCase()} Dashboard</span>
                    </div>
                  </div>
                  <div className="flex items-center gap-4 px-4">
                    <NotificationBell />
                  </div>
                </header>
                <div className="flex flex-1 flex-col overflow-hidden">
                  {children}
                </div>
              </SidebarInset>
            </SidebarProvider>
          </TooltipProvider>
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
