import { 
  dbCreateLeadBrief, 
  dbGetLastLeadBrief, 
  dbGetLeadWithContext, 
  dbGetNextReminder, 
  dbGetRecentActivities 
} from "./db";
import { 
  buildLeadBriefPrompt, 
  buildCallFollowupPrompt, 
  validateLeadAccess 
} from "./helpers";
import { generateText, Output } from "ai";
import { 
  leadBriefSchema, 
  callFollowUpSchema, 
  SaveLeadBriefRequest 
} from "./schema";
import { createAIActivity } from "../activity/service";
import { ActivityType } from "@/generated/prisma/enums";
import { Profile } from "@/generated/prisma/client";

export async function generateLeadBrief(leadId: string, user: Profile) {
  const lead = await dbGetLeadWithContext(leadId);
  if (!lead) {
    throw new Error("Lead not found");
  }

  if (!(await validateLeadAccess(lead.assignedTo?.id, user as any))) {
    throw new Error("You are not authorized to access this lead");
  }

  const [activities, nextReminder] = await Promise.all([
    dbGetRecentActivities(leadId),
    dbGetNextReminder(leadId),
  ]);

  const prompt = buildLeadBriefPrompt({
    leadContext: lead,
    recentActivities: activities,
    nextReminder: nextReminder,
  });

  const { output } = await generateText({
    model: "deepseek/deepseek-v3.2-thinking",
    output: Output.object({ schema: leadBriefSchema }),
    prompt,
  });

  await createAIActivity({
    type: ActivityType.AI_LEAD_BRIEF_GENERATED,
    leadId: leadId,
    actorId: user.id,
    content: `Lead brief generated by ${user.name}`,
  });

  return output;
}

/**
 * Assignment Task 1: Call Follow-up Service Function
 * Generates follow-up suggestions after a call.
 */
export async function generateCallFollowup(
  leadId: string,
  callOutcome: any,
  agentNotes: string | undefined,
  user: Profile,
) {
  const lead = await dbGetLeadWithContext(leadId);
  if (!lead) {
    throw new Error("Lead not found");
  }

  if (!(await validateLeadAccess(lead.assignedTo?.id, user as any))) {
    throw new Error("You are not authorized to access this lead");
  }

  // Fetch recent activities (limit 10 for focused follow-up)
  const activities = await dbGetRecentActivities(leadId, 10);

  const prompt = buildCallFollowupPrompt({
    leadContext: lead,
    recentActivities: activities,
    callOutcome,
    agentNotes,
  });

  const { output } = await generateText({
    model: "deepseek/deepseek-v3.2-thinking",
    output: Output.object({ schema: callFollowUpSchema }),
    prompt,
  });

  // Log activity for generation
  await createAIActivity({
    type: ActivityType.AI_FOLLOWUP_DRAFT_GENERATED,
    leadId: leadId,
    actorId: user.id,
    content: `Call follow-up assistant used by ${user.name}`,
  });

  return output;
}

export async function saveLeadBrief(
  request: SaveLeadBriefRequest,
  user: Profile,
) {
  const lead = await dbGetLeadWithContext(request.leadId);
  if (!lead) {
    throw new Error("Lead not found");
  }

  if (!(await validateLeadAccess(lead.assignedTo?.id, user as any))) {
    throw new Error("You are not authorized to access this lead");
  }

  const brief = await dbCreateLeadBrief(request, user);
  return brief;
}

export async function getLastLeadBrief(leadId: string, user: Profile) {
  const lead = await dbGetLeadWithContext(leadId);
  if (!lead) {
    throw new Error("Lead not found");
  }

  if (!(await validateLeadAccess(lead.assignedTo?.id, user as any))) {
    throw new Error("Unauthorized");
  }

  const row = await dbGetLastLeadBrief(leadId);
  return row ?? null;
}
